'use strict';
module.exports = (sequelize, DataTypes) => {
  const encontrista = sequelize.define('encontrista', {
    id: {type: DataTypes.INTEGER,primaryKey: true},
    nome DataTypes.STRING,
    tipo_documento DataTypes.STRING,
    numero_documento DataTypes.STRING,
    email DataTypes.STRING,
    codigo_inscricao DataTypes.STRING,
    status DataTypes.STRING,
    cancelada DataTypes.STRING,
    data_inscricao DataTypes.STRING,
    valor DataTypes.STRING,
    categoria DataTypes.STRING,
    cupom DataTypes.STRING,
    forma_pagamento DataTypes.STRING,
    quantidade_parcelas DataTypes.STRING,
    nome_lider DataTypes.STRING,
    telefone_lider DataTypes.STRING,
    numero_lider DataTypes.STRING,
    complemento_lider DataTypes.STRING,
    bairro_lider DataTypes.STRING,
    cidade_lider DataTypes.STRING,
    cep_lider DataTypes.STRING,
    telefone_Fixo DataTypes.STRING,
    outro_telefone DataTypes.STRING,
    membro_IBA DataTypes.STRING,
    participa_Celula DataTypes.STRING,
    endereco DataTypes.STRING,
    quem_inscricao DataTypes.STRING,
    email_quem DataTypes.STRING,
    tipo_documento_quem DataTypes.STRING,
    num_doc_quem DataTypes.STRING,
    ciente DataTypes.STRING,
    nome_Pai DataTypes.STRING,
    email_Pai DataTypes.STRING,
    telefone_Pai DataTypes.STRING,
    idade_no_Evento DataTypes.STRING,
    data_Nascimento DataTypes.STRING,
    membro_IBA_PAI DataTypes.STRING,
    pertence_igreja DataTypes.STRING,
    email_mae DataTypes.STRING,
    telefone_Mae DataTypes.STRING,
    nome_crianca DataTypes.STRING,
    tipo_Sanguineo DataTypes.STRING,
    idade DataTypes.STRING,
    nome_mae DataTypes.STRING,
    sexo DataTypes.STRING,
    contato DataTypes.STRING,
    alergico DataTypes.STRING,
    medicamento DataTypes.STRING,
    restricao DataTypes.STRING,
    necessidade DataTypes.STRING,
    rede DataTypes.STRING,
    url_doc DataTypes.STRING,
    quem_inscricao2 DataTypes.STRING,
    email_inscricao DataTypes.STRING,
    tipo_doc_inscricao DataTypes.STRING,
    doc_inscricao DataTypes.STRING,
    checkin DataTypes.STRING,
    nome_inscricao_lider DataTypes.STRING,
    codigo_inscricao_lider DataTypes.STRING,
    email_inscricao_lider DataTypes.STRING

  }, 
    {
     tableName: 'encontrista',
     //timestamps: false, // Se a view não tiver colunas de data de criação/atualização, desative os timestamps
   },   
  {});
  
  encontrista.associate = function(models) {   
  };
  return encontrista;
};
